---
- type: remove
  path: /instance_groups/name=vault/jobs/name=consul
- type: remove
  path: /releases/name=consul
- type: replace
  path: /instance_groups/name=vault/jobs/name=vault/properties/vault/storage
  value:
    use_s3: true
- type: replace
  path: /instance_groups/name=vault/jobs/name=vault/properties/vault/storage?/s3?
  value:
     access_key: ((s3_access_key))
     bucket: ((s3_bucket))
     region: ((s3_region))
     secret_key: ((s3_secret_key))
- type: replace
  path: /instance_groups/name=vault/instances
  value: 1
